export const supplementalWorldGuides = [
  {
    gameId: 'dream_classic_jingye_moon_v1',
    title: '入梦李白：静夜思',
    source: '静夜思',
    author: '李白',
    dynasty: '唐',
    line: '举头望明月，低头思故乡。',
    stage: '小学',
    grade: '二年级',
    semester: '上册',
    unitTitle: '月亮与乡愁',
    fullText: '床前明月光，疑是地上霜。举头望明月，低头思故乡。',
    theme: '思乡',
    motifs: ['明月', '霜', '故乡', '床前'],
    places: ['夜室', '故乡'],
    writingPoints: ['白描', '动作描写', '借景抒情'],
    translation: '床前洒满明亮月光，像地上结了一层霜。诗人抬头望月，又低头想念故乡。',
    background: '这首诗用最简洁的画面写出游子夜晚思乡的情绪。',
    annotations: [['疑', '好像。'], ['举头', '抬起头。'], ['思', '思念。']],
    worldName: '静夜月霜梦境',
    visualTone: '室内月光、霜色地面、远方故乡',
    panoramaUrl: '/assets/panoramas/moon_three_silent_4096x2048.jpg',
    coverUrl: '/assets/panoramas/moon_three_silent_4096x2048.jpg',
    themeLabel: '月白乡思',
    hotspots: ['明月', '霜光', '故乡'],
  },
  {
    gameId: 'dream_classic_gulang_moon_v1',
    title: '入梦李白：古朗月行',
    source: '古朗月行',
    author: '李白',
    dynasty: '唐',
    line: '小时不识月，呼作白玉盘。',
    stage: '小学',
    grade: '三年级',
    semester: '上册',
    unitTitle: '童心与想象',
    fullText: '小时不识月，呼作白玉盘。又疑瑶台镜，飞在青云端。',
    theme: '童真想象',
    motifs: ['月', '白玉盘', '瑶台镜', '青云'],
    places: ['青云端'],
    writingPoints: ['比喻', '想象', '儿童视角'],
    translation: '小时候不认识月亮，把它叫作白玉盘，又怀疑它是瑶台上的明镜飞在云端。',
    background: '诗句从儿童眼光写月亮，想象新鲜明亮。',
    annotations: [['呼作', '称作、叫作。'], ['瑶台', '传说中神仙居住的地方。'], ['青云端', '高高的云端。']],
    worldName: '白玉盘月梦境',
    visualTone: '圆月、云端、童年想象',
    panoramaUrl: '/assets/panoramas/moon_three_main_4096x2048.jpg',
    coverUrl: '/assets/panoramas/moon_three_main_4096x2048.jpg',
    themeLabel: '童心明月',
    hotspots: ['白玉盘', '瑶台镜', '青云'],
  },
  {
    gameId: 'dream_classic_chunxiao_birds_v1',
    title: '入梦孟浩然：春晓',
    source: '春晓',
    author: '孟浩然',
    dynasty: '唐',
    line: '夜来风雨声，花落知多少。',
    stage: '小学',
    grade: '二年级',
    semester: '下册',
    unitTitle: '春天的声音',
    fullText: '春眠不觉晓，处处闻啼鸟。夜来风雨声，花落知多少。',
    theme: '春景惜花',
    motifs: ['春眠', '啼鸟', '风雨', '落花'],
    places: ['春晨庭院'],
    writingPoints: ['听觉描写', '留白', '以小见大'],
    translation: '春天睡醒时不知天已亮，到处听见鸟叫。想起夜里风雨声，不知道花落了多少。',
    background: '诗歌用声音写春晨，也把对花落的惋惜留给读者想象。',
    annotations: [['晓', '天亮。'], ['啼鸟', '鸟鸣。'], ['知多少', '不知道有多少。']],
    worldName: '春晓鸟鸣梦境',
    visualTone: '春晨、鸟声、落花、雨后庭院',
    panoramaUrl: '/assets/panoramas/lushan_main_4096x2048.jpg',
    coverUrl: '/assets/panoramas/lushan_main_4096x2048.jpg',
    themeLabel: '春晨花雨',
    hotspots: ['啼鸟', '风雨', '落花'],
  },
  {
    gameId: 'dream_classic_stork_tower_v1',
    title: '入梦王之涣：登鹳雀楼',
    source: '登鹳雀楼',
    author: '王之涣',
    dynasty: '唐',
    line: '欲穷千里目，更上一层楼。',
    stage: '小学',
    grade: '二年级',
    semester: '下册',
    unitTitle: '登高与远望',
    fullText: '白日依山尽，黄河入海流。欲穷千里目，更上一层楼。',
    theme: '登高进取',
    motifs: ['白日', '山', '黄河', '高楼'],
    places: ['鹳雀楼', '黄河'],
    writingPoints: ['远景描写', '哲理表达', '空间推进'],
    translation: '夕阳依着群山落下，黄河奔向大海。想看得更远，就要再登上一层楼。',
    background: '诗句由壮阔景象转入人生道理，适合讲登高与进取。',
    annotations: [['白日', '太阳。'], ['穷', '尽、达到极点。'], ['千里目', '很远的视野。']],
    worldName: '鹳雀楼远望梦境',
    visualTone: '高楼、夕阳、黄河入海',
    panoramaUrl: '/assets/panoramas/yellow_river_main_4096x2048.jpg',
    coverUrl: '/assets/panoramas/yellow_river_main_4096x2048.jpg',
    themeLabel: '登高黄河',
    hotspots: ['白日', '黄河', '高楼'],
  },
  {
    gameId: 'dream_classic_liangzhou_pass_v1',
    title: '入梦王之涣：凉州词',
    source: '凉州词',
    author: '王之涣',
    dynasty: '唐',
    line: '羌笛何须怨杨柳，春风不度玉门关。',
    stage: '初中',
    grade: '七年级',
    semester: '上册',
    unitTitle: '边塞与乡愁',
    fullText: '黄河远上白云间，一片孤城万仞山。羌笛何须怨杨柳，春风不度玉门关。',
    theme: '边塞苍凉',
    motifs: ['黄河', '白云', '孤城', '羌笛'],
    places: ['玉门关', '边塞'],
    writingPoints: ['边塞意象', '反问', '借景抒情'],
    translation: '黄河仿佛远上白云之间，一座孤城立在万仞高山中。羌笛何必吹出怨杨柳的曲调，春风本就吹不到玉门关。',
    background: '诗歌写边塞辽远荒寒，也写戍边人的乡愁。',
    annotations: [['羌笛', '古代羌族乐器。'], ['杨柳', '古曲名，也有送别含义。'], ['度', '越过。']],
    worldName: '玉门孤城梦境',
    visualTone: '黄河、白云、孤城、边关',
    panoramaUrl: '/assets/panoramas/yellow_river_canyon_4096x2048.jpg',
    coverUrl: '/assets/panoramas/yellow_river_canyon_4096x2048.jpg',
    themeLabel: '边关黄河',
    hotspots: ['孤城', '羌笛', '玉门关'],
  },
  {
    gameId: 'dream_classic_desert_envoy_v1',
    title: '入梦王维：使至塞上',
    source: '使至塞上',
    author: '王维',
    dynasty: '唐',
    line: '大漠孤烟直，长河落日圆。',
    stage: '初中',
    grade: '八年级',
    semester: '上册',
    unitTitle: '边塞画面',
    fullText: '单车欲问边，属国过居延。征蓬出汉塞，归雁入胡天。大漠孤烟直，长河落日圆。萧关逢候骑，都护在燕然。',
    theme: '边塞壮阔',
    motifs: ['大漠', '孤烟', '长河', '落日'],
    places: ['塞上', '居延', '萧关'],
    writingPoints: ['对仗', '画面构图', '情景交融'],
    translation: '诗人出使边塞，看到大漠中孤烟笔直升起，长河尽头落日浑圆。',
    background: '王维以极简构图写出边塞的辽阔和苍茫。',
    annotations: [['单车', '轻车简从。'], ['征蓬', '飘飞的蓬草，比喻漂泊。'], ['候骑', '侦察骑兵。']],
    worldName: '大漠长河梦境',
    visualTone: '大漠、孤烟、长河、落日',
    panoramaUrl: '/assets/panoramas/yellow_river_source_4096x2048.jpg',
    coverUrl: '/assets/panoramas/yellow_river_source_4096x2048.jpg',
    themeLabel: '大漠落日',
    hotspots: ['孤烟', '长河', '落日'],
  },
  {
    gameId: 'dream_classic_autumn_mountain_v1',
    title: '入梦王维：山居秋暝',
    source: '山居秋暝',
    author: '王维',
    dynasty: '唐',
    line: '明月松间照，清泉石上流。',
    stage: '初中',
    grade: '八年级',
    semester: '上册',
    unitTitle: '山水与清境',
    fullText: '空山新雨后，天气晚来秋。明月松间照，清泉石上流。竹喧归浣女，莲动下渔舟。随意春芳歇，王孙自可留。',
    theme: '山水清幽',
    motifs: ['明月', '松', '清泉', '竹'],
    places: ['空山', '山居'],
    writingPoints: ['动静结合', '以声衬静', '意境营造'],
    translation: '雨后的空山秋意渐浓，明月照在松林之间，清泉在石上流过。',
    background: '诗歌营造清新宁静的山居意境，体现王维诗中有画的特点。',
    annotations: [['暝', '傍晚。'], ['浣女', '洗衣归来的女子。'], ['春芳歇', '春天花草凋谢。']],
    worldName: '秋山松泉梦境',
    visualTone: '雨后空山、松间明月、石上清泉',
    panoramaUrl: '/assets/panoramas/branch_silent_peak_4096x2048.jpg',
    coverUrl: '/assets/panoramas/branch_silent_peak_4096x2048.jpg',
    themeLabel: '松泉秋月',
    hotspots: ['明月', '松林', '清泉'],
  },
  {
    gameId: 'dream_classic_luchai_echo_v1',
    title: '入梦王维：鹿柴',
    source: '鹿柴',
    author: '王维',
    dynasty: '唐',
    line: '返景入深林，复照青苔上。',
    stage: '小学',
    grade: '四年级',
    semester: '上册',
    unitTitle: '空山与回声',
    fullText: '空山不见人，但闻人语响。返景入深林，复照青苔上。',
    theme: '空山幽静',
    motifs: ['空山', '人语', '返景', '青苔'],
    places: ['鹿柴', '深林'],
    writingPoints: ['以声衬静', '光影描写', '留白'],
    translation: '空山里看不见人，只听到人说话的回声。夕阳返照进入深林，又照在青苔上。',
    background: '诗歌用声音和光影写出山林幽静。',
    annotations: [['柴', '同“寨”，栅栏。'], ['返景', '夕阳返照的光。'], ['复', '又。']],
    worldName: '鹿柴深林梦境',
    visualTone: '空山、回声、夕光、青苔',
    panoramaUrl: '/assets/panoramas/branch_silent_peak_4096x2048.webp',
    coverUrl: '/assets/panoramas/branch_silent_peak_4096x2048.webp',
    themeLabel: '空山返照',
    hotspots: ['空山', '人语', '青苔'],
  },
  {
    gameId: 'dream_classic_yuaner_farewell_v1',
    title: '入梦王维：送元二使安西',
    source: '送元二使安西',
    author: '王维',
    dynasty: '唐',
    line: '劝君更尽一杯酒，西出阳关无故人。',
    stage: '小学',
    grade: '六年级',
    semester: '上册',
    unitTitle: '送别与深情',
    fullText: '渭城朝雨浥轻尘，客舍青青柳色新。劝君更尽一杯酒，西出阳关无故人。',
    theme: '送别',
    motifs: ['朝雨', '柳色', '酒', '阳关'],
    places: ['渭城', '阳关', '安西'],
    writingPoints: ['借景抒情', '直抒胸臆', '送别意象'],
    translation: '渭城清晨的雨湿润了尘土，客舍旁柳色青青。请你再喝一杯酒，出了阳关往西就难见老朋友了。',
    background: '诗歌把送别的不舍写进雨、柳和酒中。',
    annotations: [['浥', '湿润。'], ['更尽', '再喝完。'], ['阳关', '古代关隘名。']],
    worldName: '渭城朝雨梦境',
    visualTone: '朝雨、客舍、柳色、送别酒',
    panoramaUrl: '/assets/panoramas/yangtze_farewell_pavilion_4096x2048.jpg',
    coverUrl: '/assets/panoramas/yangtze_farewell_pavilion_4096x2048.jpg',
    themeLabel: '雨柳送别',
    hotspots: ['朝雨', '柳色', '酒杯'],
  },
  {
    gameId: 'dream_classic_dufu_wangyue_v1',
    title: '入梦杜甫：望岳',
    source: '望岳',
    author: '杜甫',
    dynasty: '唐',
    line: '会当凌绝顶，一览众山小。',
    stage: '初中',
    grade: '七年级',
    semester: '下册',
    unitTitle: '登临与抱负',
    fullText: '岱宗夫如何？齐鲁青未了。造化钟神秀，阴阳割昏晓。荡胸生曾云，决眦入归鸟。会当凌绝顶，一览众山小。',
    theme: '壮志抱负',
    motifs: ['泰山', '层云', '归鸟', '绝顶'],
    places: ['泰山', '齐鲁'],
    writingPoints: ['远望近观', '夸张', '托物言志'],
    translation: '泰山横跨齐鲁，青色无边。诗人望见层云和归鸟，立志登上最高峰俯瞰众山。',
    background: '青年杜甫借望泰山表达远大志向。',
    annotations: [['岱宗', '泰山。'], ['决眦', '睁大眼睛。'], ['会当', '终当、一定要。']],
    worldName: '泰山绝顶梦境',
    visualTone: '高山、层云、归鸟、远望',
    panoramaUrl: '/assets/panoramas/dream_li_bai_tianshan_cloudsea_main.png',
    coverUrl: '/assets/panoramas/dream_li_bai_tianshan_cloudsea_main.png',
    themeLabel: '泰山层云',
    hotspots: ['泰山', '层云', '绝顶'],
  },
  {
    gameId: 'dream_classic_dufu_spring_view_v1',
    title: '入梦杜甫：春望',
    source: '春望',
    author: '杜甫',
    dynasty: '唐',
    line: '感时花溅泪，恨别鸟惊心。',
    stage: '初中',
    grade: '八年级',
    semester: '上册',
    unitTitle: '家国与离乱',
    fullText: '国破山河在，城春草木深。感时花溅泪，恨别鸟惊心。烽火连三月，家书抵万金。白头搔更短，浑欲不胜簪。',
    theme: '忧国思家',
    motifs: ['山河', '草木', '花', '鸟'],
    places: ['长安'],
    writingPoints: ['以乐景写哀情', '对偶', '情景交融'],
    translation: '国都残破但山河仍在，春天城中草木深密。花鸟本是春景，却因伤时离别而让人落泪惊心。',
    background: '安史之乱中，杜甫把家国忧思写入春日景物。',
    annotations: [['国破', '国都沦陷。'], ['烽火', '战火。'], ['浑欲', '简直要。']],
    worldName: '春城草木梦境',
    visualTone: '春城、草木、花鸟、烽火远影',
    panoramaUrl: '/assets/panoramas/dream_generated_changsha_1925_branch_b.png',
    coverUrl: '/assets/panoramas/dream_generated_changsha_1925_branch_b.png',
    themeLabel: '春望家国',
    hotspots: ['草木', '花泪', '家书'],
  },
  {
    gameId: 'dream_classic_dufu_quatrain_v1',
    title: '入梦杜甫：绝句',
    source: '绝句',
    author: '杜甫',
    dynasty: '唐',
    line: '两个黄鹂鸣翠柳，一行白鹭上青天。',
    stage: '小学',
    grade: '三年级',
    semester: '下册',
    unitTitle: '色彩中的春天',
    fullText: '两个黄鹂鸣翠柳，一行白鹭上青天。窗含西岭千秋雪，门泊东吴万里船。',
    theme: '春日明丽',
    motifs: ['黄鹂', '翠柳', '白鹭', '青天'],
    places: ['草堂', '西岭', '东吴'],
    writingPoints: ['色彩描写', '对仗', '动静结合'],
    translation: '两只黄鹂在翠绿柳枝间鸣叫，一行白鹭飞上青天。窗中望见西岭积雪，门外停着远来的船。',
    background: '诗歌像一幅色彩鲜明的春日画。',
    annotations: [['黄鹂', '黄莺。'], ['窗含', '从窗中望见，好像含在窗框里。'], ['泊', '停船。']],
    worldName: '翠柳白鹭梦境',
    visualTone: '黄鹂、翠柳、白鹭、青天',
    panoramaUrl: '/assets/panoramas/yangtze_farewell_horizon_4096x2048.jpg',
    coverUrl: '/assets/panoramas/yangtze_farewell_horizon_4096x2048.jpg',
    themeLabel: '明丽春景',
    hotspots: ['黄鹂', '白鹭', '远船'],
  },
  {
    gameId: 'dream_classic_grass_farewell_v1',
    title: '入梦白居易：赋得古原草送别',
    source: '赋得古原草送别',
    author: '白居易',
    dynasty: '唐',
    line: '野火烧不尽，春风吹又生。',
    stage: '小学',
    grade: '三年级',
    semester: '上册',
    unitTitle: '草原与生命',
    fullText: '离离原上草，一岁一枯荣。野火烧不尽，春风吹又生。远芳侵古道，晴翠接荒城。又送王孙去，萋萋满别情。',
    theme: '生命与送别',
    motifs: ['原草', '野火', '春风', '古道'],
    places: ['古原', '古道'],
    writingPoints: ['比兴', '对比', '托物言情'],
    translation: '原野上的草一年一枯一荣，野火烧不尽，春风吹来又会生长。',
    background: '诗歌借草的生命力写送别，也写坚韧生长。',
    annotations: [['离离', '草木茂盛的样子。'], ['枯荣', '枯萎和繁荣。'], ['王孙', '远行的人。']],
    worldName: '古原春草梦境',
    visualTone: '原野、春草、古道、送别',
    panoramaUrl: '/assets/panoramas/dream_li_bai_jingmen_wilderness_main.png',
    coverUrl: '/assets/panoramas/dream_li_bai_jingmen_wilderness_main.png',
    themeLabel: '古原春风',
    hotspots: ['原草', '野火', '春风'],
  },
  {
    gameId: 'dream_classic_qiantang_spring_v1',
    title: '入梦白居易：钱塘湖春行',
    source: '钱塘湖春行',
    author: '白居易',
    dynasty: '唐',
    line: '几处早莺争暖树，谁家新燕啄春泥。',
    stage: '初中',
    grade: '七年级',
    semester: '上册',
    unitTitle: '湖上春行',
    fullText: '孤山寺北贾亭西，水面初平云脚低。几处早莺争暖树，谁家新燕啄春泥。乱花渐欲迷人眼，浅草才能没马蹄。最爱湖东行不足，绿杨阴里白沙堤。',
    theme: '湖上春景',
    motifs: ['早莺', '新燕', '乱花', '浅草'],
    places: ['钱塘湖', '白沙堤'],
    writingPoints: ['移步换景', '细节描写', '动静结合'],
    translation: '诗人春游钱塘湖，看早莺争向暖树，新燕啄取春泥，花草渐盛。',
    background: '诗歌用连续细节写出西湖早春的生机。',
    annotations: [['云脚', '接近水面的低云。'], ['没', '遮没。'], ['行不足', '走不够，舍不得离开。']],
    worldName: '钱塘早春梦境',
    visualTone: '湖面、早莺、新燕、浅草',
    panoramaUrl: '/assets/panoramas/yangtze_farewell_horizon_4096x2048.webp',
    coverUrl: '/assets/panoramas/yangtze_farewell_horizon_4096x2048.webp',
    themeLabel: '湖上早春',
    hotspots: ['早莺', '新燕', '浅草'],
  },
  {
    gameId: 'dream_classic_jiangxue_boat_v1',
    title: '入梦柳宗元：江雪',
    source: '江雪',
    author: '柳宗元',
    dynasty: '唐',
    line: '孤舟蓑笠翁，独钓寒江雪。',
    stage: '小学',
    grade: '四年级',
    semester: '下册',
    unitTitle: '雪景与孤独',
    fullText: '千山鸟飞绝，万径人踪灭。孤舟蓑笠翁，独钓寒江雪。',
    theme: '寒江孤寂',
    motifs: ['千山', '万径', '孤舟', '雪'],
    places: ['寒江'],
    writingPoints: ['夸张', '白描', '烘托'],
    translation: '群山不见飞鸟，所有道路不见人踪。只有一叶孤舟上，披蓑戴笠的老人在寒江雪中独钓。',
    background: '诗歌以极寒极静的画面衬托孤高心境。',
    annotations: [['绝', '没有了。'], ['踪', '踪迹。'], ['蓑笠', '蓑衣和斗笠。']],
    worldName: '寒江独钓梦境',
    visualTone: '雪山、寒江、孤舟、蓑笠翁',
    panoramaUrl: '/assets/panoramas/dream_li_bai_tianshan_cloudsea_main.png',
    coverUrl: '/assets/panoramas/dream_li_bai_tianshan_cloudsea_main.png',
    themeLabel: '寒江雪静',
    hotspots: ['千山', '孤舟', '寒雪'],
  },
  {
    gameId: 'dream_classic_fengqiao_bells_v1',
    title: '入梦张继：枫桥夜泊',
    source: '枫桥夜泊',
    author: '张继',
    dynasty: '唐',
    line: '姑苏城外寒山寺，夜半钟声到客船。',
    stage: '小学',
    grade: '五年级',
    semester: '上册',
    unitTitle: '夜泊与钟声',
    fullText: '月落乌啼霜满天，江枫渔火对愁眠。姑苏城外寒山寺，夜半钟声到客船。',
    theme: '羁旅愁思',
    motifs: ['月落', '乌啼', '江枫', '钟声'],
    places: ['枫桥', '寒山寺', '客船'],
    writingPoints: ['听觉描写', '意象叠加', '情景交融'],
    translation: '月亮落下，乌鸦啼叫，霜气满天；江边枫树和渔火对着难眠的旅人，半夜钟声传到客船。',
    background: '诗歌用夜景和钟声写旅途愁绪。',
    annotations: [['夜泊', '夜里停船。'], ['江枫', '江边枫树。'], ['姑苏', '苏州。']],
    worldName: '枫桥钟声梦境',
    visualTone: '夜月、渔火、客船、寺钟',
    panoramaUrl: '/assets/panoramas/moon_three_shadow_4096x2048.jpg',
    coverUrl: '/assets/panoramas/moon_three_shadow_4096x2048.jpg',
    themeLabel: '夜泊钟声',
    hotspots: ['月落', '渔火', '钟声'],
  },
  {
    gameId: 'dream_classic_guazhou_moon_v1',
    title: '入梦王安石：泊船瓜洲',
    source: '泊船瓜洲',
    author: '王安石',
    dynasty: '宋',
    line: '春风又绿江南岸，明月何时照我还。',
    stage: '小学',
    grade: '五年级',
    semester: '下册',
    unitTitle: '春风与归心',
    fullText: '京口瓜洲一水间，钟山只隔数重山。春风又绿江南岸，明月何时照我还。',
    theme: '思乡归心',
    motifs: ['春风', '江南岸', '明月', '归舟'],
    places: ['瓜洲', '京口', '钟山'],
    writingPoints: ['炼字', '借景抒情', '空间对照'],
    translation: '京口和瓜洲只隔一条江，钟山也只隔几重山。春风又吹绿江南岸，明月什么时候照我回乡？',
    background: '诗中“绿”字写出春风的动态，也写出诗人的归心。',
    annotations: [['一水间', '隔着一条水。'], ['绿', '使变绿。'], ['还', '回去。']],
    worldName: '瓜洲春风梦境',
    visualTone: '江岸、春风、明月、归舟',
    panoramaUrl: '/assets/panoramas/yangtze_farewell_sail_4096x2048.jpg',
    coverUrl: '/assets/panoramas/yangtze_farewell_sail_4096x2048.jpg',
    themeLabel: '春风归舟',
    hotspots: ['江南岸', '春风', '明月'],
  },
  {
    gameId: 'dream_classic_xilin_wall_v1',
    title: '入梦苏轼：题西林壁',
    source: '题西林壁',
    author: '苏轼',
    dynasty: '宋',
    line: '不识庐山真面目，只缘身在此山中。',
    stage: '小学',
    grade: '六年级',
    semester: '上册',
    unitTitle: '角度与哲理',
    fullText: '横看成岭侧成峰，远近高低各不同。不识庐山真面目，只缘身在此山中。',
    theme: '观察角度',
    motifs: ['庐山', '岭', '峰', '山中'],
    places: ['庐山', '西林寺'],
    writingPoints: ['哲理表达', '角度变化', '借景说理'],
    translation: '从横面看是山岭，从侧面看成山峰，远近高低都不同。看不清庐山真面目，只因自己就在山中。',
    background: '诗歌由看山引出认识事物要换角度的道理。',
    annotations: [['缘', '因为。'], ['真面目', '真实整体面貌。'], ['横看', '从正面横向看。']],
    worldName: '庐山多面梦境',
    visualTone: '山岭、峰峦、云雾、视角变化',
    panoramaUrl: '/assets/panoramas/lushan_main_4096x2048.jpg',
    coverUrl: '/assets/panoramas/lushan_main_4096x2048.jpg',
    themeLabel: '庐山哲理',
    hotspots: ['山岭', '峰峦', '山中'],
  },
  {
    gameId: 'dream_classic_westlake_rain_v1',
    title: '入梦苏轼：饮湖上初晴后雨',
    source: '饮湖上初晴后雨',
    author: '苏轼',
    dynasty: '宋',
    line: '欲把西湖比西子，淡妆浓抹总相宜。',
    stage: '小学',
    grade: '五年级',
    semester: '上册',
    unitTitle: '西湖与比喻',
    fullText: '水光潋滟晴方好，山色空蒙雨亦奇。欲把西湖比西子，淡妆浓抹总相宜。',
    theme: '西湖审美',
    motifs: ['水光', '山色', '雨', '西子'],
    places: ['西湖'],
    writingPoints: ['比喻', '对比', '情景交融'],
    translation: '晴天西湖水光荡漾很美，雨天山色迷蒙也奇妙。若把西湖比作西施，淡妆浓妆都合适。',
    background: '诗人用西施比西湖，写出晴雨皆美的审美感受。',
    annotations: [['潋滟', '水波闪动的样子。'], ['空蒙', '迷茫朦胧。'], ['西子', '西施。']],
    worldName: '西湖晴雨梦境',
    visualTone: '湖水、雨雾、山色、晴光',
    panoramaUrl: '/assets/panoramas/dream_li_bai_moon_mirror_sea_tower_main.png',
    coverUrl: '/assets/panoramas/dream_li_bai_moon_mirror_sea_tower_main.png',
    themeLabel: '西湖晴雨',
    hotspots: ['水光', '山色', '西子'],
  },
  {
    gameId: 'dream_classic_mid_autumn_moon_v1',
    title: '入梦苏轼：水调歌头',
    source: '水调歌头',
    author: '苏轼',
    dynasty: '宋',
    line: '但愿人长久，千里共婵娟。',
    stage: '初中',
    grade: '七年级',
    semester: '下册',
    unitTitle: '明月与人生',
    fullText: '明月几时有？把酒问青天。不知天上宫阙，今夕是何年。人有悲欢离合，月有阴晴圆缺，此事古难全。但愿人长久，千里共婵娟。',
    theme: '亲情与旷达',
    motifs: ['明月', '酒', '青天', '婵娟'],
    places: ['中秋夜', '青天'],
    writingPoints: ['议论抒情', '想象', '哲理表达'],
    translation: '诗人中秋望月，想到人生悲欢离合和月亮阴晴圆缺，最终祝愿亲人长久平安，共赏明月。',
    background: '词中既有怀人之情，也有超越遗憾的旷达。',
    annotations: [['宫阙', '宫殿。'], ['婵娟', '美好的月色，也指月亮。'], ['古难全', '自古难以圆满。']],
    worldName: '中秋共月梦境',
    visualTone: '明月、酒盏、青天、远方亲人',
    panoramaUrl: '/assets/panoramas/branch_moon_toast_4096x2048.jpg',
    coverUrl: '/assets/panoramas/branch_moon_toast_4096x2048.jpg',
    themeLabel: '中秋明月',
    hotspots: ['明月', '酒盏', '婵娟'],
  },
  {
    gameId: 'dream_classic_shanxi_village_v1',
    title: '入梦陆游：游山西村',
    source: '游山西村',
    author: '陆游',
    dynasty: '宋',
    line: '山重水复疑无路，柳暗花明又一村。',
    stage: '初中',
    grade: '七年级',
    semester: '下册',
    unitTitle: '村行与转机',
    fullText: '莫笑农家腊酒浑，丰年留客足鸡豚。山重水复疑无路，柳暗花明又一村。箫鼓追随春社近，衣冠简朴古风存。从今若许闲乘月，拄杖无时夜叩门。',
    theme: '乡村与转机',
    motifs: ['山重', '水复', '柳暗', '花明'],
    places: ['山西村'],
    writingPoints: ['对偶', '哲理表达', '移步换景'],
    translation: '山峦重叠水路曲折，正疑无路可走，却在柳色花光中又见一个村庄。',
    background: '诗句由村行景象引申为困境中出现转机。',
    annotations: [['腊酒', '腊月酿的酒。'], ['鸡豚', '鸡和猪，指待客食物。'], ['无时', '随时。']],
    worldName: '柳暗花明梦境',
    visualTone: '山路、水道、柳荫、村庄',
    panoramaUrl: '/assets/panoramas/dream_li_bai_jingmen_wilderness_main.png',
    coverUrl: '/assets/panoramas/dream_li_bai_jingmen_wilderness_main.png',
    themeLabel: '山村转机',
    hotspots: ['山重', '柳暗', '村庄'],
  },
  {
    gameId: 'dream_classic_battle_song_v1',
    title: '入梦辛弃疾：破阵子',
    source: '破阵子·为陈同甫赋壮词以寄之',
    author: '辛弃疾',
    dynasty: '宋',
    line: '了却君王天下事，赢得生前身后名。',
    stage: '初中',
    grade: '九年级',
    semester: '上册',
    unitTitle: '壮志与现实',
    fullText: '醉里挑灯看剑，梦回吹角连营。八百里分麾下炙，五十弦翻塞外声。沙场秋点兵。马作的卢飞快，弓如霹雳弦惊。了却君王天下事，赢得生前身后名。可怜白发生！',
    theme: '报国壮志',
    motifs: ['剑', '角声', '沙场', '白发'],
    places: ['军营', '沙场'],
    writingPoints: ['梦境叙事', '对比', '豪放词风'],
    translation: '词人在醉梦中回到军营沙场，想完成报国大业、赢得功名，醒来却感叹白发已生。',
    background: '辛弃疾把理想战场和现实失意强烈对照，情感悲壮。',
    annotations: [['挑灯', '拨亮灯火。'], ['八百里', '牛的代称，也指军中宴饮。'], ['的卢', '骏马名。']],
    worldName: '沙场秋兵梦境',
    visualTone: '军营、剑光、角声、秋点兵',
    panoramaUrl: '/assets/panoramas/dream_generated_silver_saddle_meteor_branch_b.png',
    coverUrl: '/assets/panoramas/dream_generated_silver_saddle_meteor_branch_b.png',
    themeLabel: '沙场壮词',
    hotspots: ['剑光', '角声', '沙场'],
  },
  {
    gameId: 'dream_classic_xijiang_moon_v1',
    title: '入梦辛弃疾：西江月·夜行黄沙道中',
    source: '西江月·夜行黄沙道中',
    author: '辛弃疾',
    dynasty: '宋',
    line: '明月别枝惊鹊，清风半夜鸣蝉。',
    stage: '初中',
    grade: '七年级',
    semester: '上册',
    unitTitle: '乡村夜行',
    fullText: '明月别枝惊鹊，清风半夜鸣蝉。稻花香里说丰年，听取蛙声一片。七八个星天外，两三点雨山前。旧时茅店社林边，路转溪桥忽见。',
    theme: '乡村夜景',
    motifs: ['明月', '清风', '稻花', '蛙声'],
    places: ['黄沙道', '溪桥'],
    writingPoints: ['多感官描写', '动静结合', '白描'],
    translation: '明月惊动枝头喜鹊，半夜清风中蝉鸣。稻花香里仿佛谈着丰年，耳边是一片蛙声。',
    background: '词作以夜行见闻写乡村夏夜的生机。',
    annotations: [['别枝', '斜出的树枝。'], ['社林', '土地庙旁的树林。'], ['忽见', '忽然出现。']],
    worldName: '黄沙道夜行梦境',
    visualTone: '明月、清风、稻花、溪桥',
    panoramaUrl: '/assets/panoramas/branch_moon_bridge_4096x2048.jpg',
    coverUrl: '/assets/panoramas/branch_moon_bridge_4096x2048.jpg',
    themeLabel: '乡村月夜',
    hotspots: ['明月', '稻花', '溪桥'],
  },
  {
    gameId: 'dream_classic_canghai_sea_v1',
    title: '入梦曹操：观沧海',
    source: '观沧海',
    author: '曹操',
    dynasty: '东汉',
    line: '日月之行，若出其中；星汉灿烂，若出其里。',
    stage: '初中',
    grade: '七年级',
    semester: '上册',
    unitTitle: '沧海与胸怀',
    fullText: '东临碣石，以观沧海。水何澹澹，山岛竦峙。树木丛生，百草丰茂。秋风萧瑟，洪波涌起。日月之行，若出其中；星汉灿烂，若出其里。幸甚至哉，歌以咏志。',
    theme: '壮阔胸怀',
    motifs: ['沧海', '山岛', '洪波', '日月'],
    places: ['碣石', '沧海'],
    writingPoints: ['虚实结合', '宏大想象', '托物言志'],
    translation: '诗人登临碣石观海，看到海水浩荡、山岛耸立，又想象日月星汉都从大海中运行升起。',
    background: '诗歌以大海景象表现开阔胸襟和远大志向。',
    annotations: [['澹澹', '水波动荡的样子。'], ['竦峙', '高高耸立。'], ['星汉', '银河。']],
    worldName: '碣石沧海梦境',
    visualTone: '大海、山岛、洪波、日月星汉',
    panoramaUrl: '/assets/panoramas/yellow_river_sea_4096x2048.jpg',
    coverUrl: '/assets/panoramas/yellow_river_sea_4096x2048.jpg',
    themeLabel: '沧海星汉',
    hotspots: ['沧海', '洪波', '星汉'],
  },
  {
    gameId: 'dream_classic_chile_sky_v1',
    title: '入梦北朝民歌：敕勒歌',
    source: '敕勒歌',
    author: '北朝民歌',
    dynasty: '南北朝',
    line: '天苍苍，野茫茫，风吹草低见牛羊。',
    stage: '小学',
    grade: '二年级',
    semester: '下册',
    unitTitle: '草原与天地',
    fullText: '敕勒川，阴山下。天似穹庐，笼盖四野。天苍苍，野茫茫，风吹草低见牛羊。',
    theme: '草原辽阔',
    motifs: ['天空', '草原', '风', '牛羊'],
    places: ['敕勒川', '阴山'],
    writingPoints: ['民歌语言', '比喻', '空间描写'],
    translation: '敕勒川在阴山脚下，天空像圆顶帐篷覆盖四野。天空苍茫，原野辽阔，风吹草低露出牛羊。',
    background: '民歌用朴素语言写出北方草原的辽阔。',
    annotations: [['穹庐', '游牧民族的圆顶帐篷。'], ['四野', '四面的原野。'], ['见', '同“现”，显现。']],
    worldName: '敕勒草原梦境',
    visualTone: '苍天、草原、风、牛羊',
    panoramaUrl: '/assets/panoramas/dream_li_bai_jingmen_wilderness_main.png',
    coverUrl: '/assets/panoramas/dream_li_bai_jingmen_wilderness_main.png',
    themeLabel: '草原天地',
    hotspots: ['苍天', '草原', '牛羊'],
  },
];

export const supplementalGuides = Object.fromEntries(
  supplementalWorldGuides.map(({ gameId, title, worldName, visualTone, panoramaUrl, coverUrl, themeLabel, hotspots, ...guide }) => [
    guide.source,
    guide,
  ]),
);
